#!/usr/bin/env python3

import os
import sys
import time

from TamperDaemon import TamperDaemon

if __name__ == '__main__':

    if len(sys.argv) == 1:
        sys.exit ("Usage: " + sys.argv[0] + " [start|stop|restart]");

    action = sys.argv[1]

    pidfile = "/var/run/tamperd.pid"
    daemon = TamperDaemon.Daemon(pidfile=pidfile)

    if action == "start":
        daemon.start()

    elif action == "stop":
        daemon.cleanup ()
        daemon.stop ()

    elif action == "restart":
        daemon.cleanup ()
        daemon.stop ()
        daemon.start ()
