#!/bin/sh

set -e

# source debconf library
. /usr/share/debconf/confmodule

case "$1" in

  remove|upgrade|deconfigure)
    if [ -d "/usr/sbin/TamperDaemon/__pycache__/" ]; then
        rm -r  /usr/sbin/TamperDaemon/__pycache__/
    fi
    service tamperd stop
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

db_stop

exit 0

